In [15]:
import pandas as pd
df_EI=pd.read_csv('MBTI_EI.csv',index_col=0)
df_SN=pd.read_csv('MBTI_SN.csv',index_col=0)
df_TF=pd.read_csv('MBTI_TF.csv',index_col=0)
df_PJ=pd.read_csv('MBTI_PJ.csv',index_col=0)



In [18]:
df_all=pd.read_csv('MBTI_ALL.csv',index_col=0)
df_raw=pd.read_csv('MBTI 500.csv')

In [2]:
import pickle

with open('MBTI500.pkl','wb') as f:
    pickle.dump(df_raw, f)

with open('MBTI_EI.pkl','wb') as f:
    pickle.dump(df_EI, f)

with open('MBTI_SN.pkl','wb') as f:
    pickle.dump(df_SN, f)

with open('MBTI_TF.pkl','wb') as f:
    pickle.dump(df_TF, f)

with open('MBTI_PJ.pkl','wb') as f:
    pickle.dump(df_PJ, f)

NameError: name 'df_raw' is not defined

In [1]:
import pickle
import numpy as np
EI = np.load('EI_test.pkl',allow_pickle=True)
SN = np.load('SN_test.pkl',allow_pickle=True)
TF = np.load('TF_test.pkl',allow_pickle=True)
PJ = np.load('PJ_test.pkl',allow_pickle=True)

In [2]:
EI_all=np.concatenate(EI)
SN_all=np.concatenate(SN)
TF_all=np.concatenate(TF)
PJ_all=np.concatenate(PJ)

In [4]:
import pickle
import numpy as np
EI_label = np.load('EI_test_label.pkl',allow_pickle=True)
SN_label = np.load('SN_test_label.pkl',allow_pickle=True)
TF_label = np.load('TF_test_label.pkl',allow_pickle=True)
PJ_label = np.load('PJ_test_label.pkl',allow_pickle=True)

In [5]:
PJ_label

array([array([0, 0, 0, ..., 1, 1, 0], dtype=int64),
       array([0, 1, 0, ..., 0, 0, 1], dtype=int64),
       array([1, 0, 1, ..., 0, 0, 1], dtype=int64),
       array([1, 0, 1, ..., 0, 0, 1], dtype=int64),
       array([0, 1, 1, ..., 0, 0, 0], dtype=int64),
       array([0, 0, 0, ..., 0, 0, 0], dtype=int64),
       array([0, 0, 0, ..., 1, 0, 0], dtype=int64),
       array([1, 0, 0, ..., 1, 1, 0], dtype=int64),
       array([1, 1, 1, ..., 0, 0, 0], dtype=int64),
       array([1, 1, 1, ..., 1, 0, 0], dtype=int64),
       array([0, 1, 1, 0], dtype=int64)], dtype=object)

In [6]:
EI_all_label=np.concatenate(EI_label)
SN_all_label=np.concatenate(SN_label)
TF_all_label=np.concatenate(TF_label)
PJ_all_label=np.concatenate(PJ_label)

In [10]:
import collections
collections.Counter(PJ_all_label)


Counter({0: 12332, 1: 8882})

In [5]:
from sklearn.metrics import classification_report

print(classification_report(y_pred=EI_all,y_true=EI_all_label))

              precision    recall  f1-score   support

           0       0.85      0.90      0.88      5146
           1       0.97      0.95      0.96     16068

    accuracy                           0.94     21214
   macro avg       0.91      0.93      0.92     21214
weighted avg       0.94      0.94      0.94     21214



In [6]:
print(classification_report(y_pred=SN_all,y_true=SN_all_label))

              precision    recall  f1-score   support

           0       0.96      0.79      0.86      1854
           1       0.98      1.00      0.99     19360

    accuracy                           0.98     21214
   macro avg       0.97      0.89      0.93     21214
weighted avg       0.98      0.98      0.98     21214



In [7]:
print(classification_report(y_pred=TF_all,y_true=TF_all_label))

              precision    recall  f1-score   support

           0       0.93      0.98      0.95     13887
           1       0.95      0.85      0.90      7327

    accuracy                           0.93     21214
   macro avg       0.94      0.92      0.93     21214
weighted avg       0.94      0.93      0.93     21214



In [8]:
print(classification_report(y_pred=PJ_all,y_true=PJ_all_label))

              precision    recall  f1-score   support

           0       0.94      0.94      0.94     12332
           1       0.92      0.92      0.92      8882

    accuracy                           0.93     21214
   macro avg       0.93      0.93      0.93     21214
weighted avg       0.93      0.93      0.93     21214



In [9]:
pred_all=[]
for a,b,c,d in zip(EI_all,SN_all,TF_all,PJ_all):
    pred_all.append([a,b,c,d])

In [10]:
label_all=[]
for a,b,c,d in zip(EI_all_label,SN_all_label,TF_all_label,PJ_all_label):
    label_all.append([a,b,c,d])

In [11]:
accuracy=[]
for pred, label in zip(pred_all,label_all):
    if pred == label:
        accuracy.append(1)
    else:
        accuracy.append(0)

In [12]:
np.array(accuracy).mean()

0.8085698123880456

In [13]:
accuracy.count(1)

17153

In [14]:
accuracy.count(0)

4061